### ISSUE TITLE
Error: Meteor code must always run within a Fiber

### ISSUE THREAD

**Issue by elie222** [meteorhacks/picker#3]
My mup logs:

spiderable: phantomjs failed: null
stderr:
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
    at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
    at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
    at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
    at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
    at Object.router (packages/iron:router/lib/router.js:15:1)
    at next (/opt/draftapp/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at processNextSubRouter (packages/meteorhacks:picker/lib/implementation.js:74:1)

**Comment by arunoda** [comment]
This doesn't seems like a picker's error. It's passing the http request to IR and that's where the error throws. But, I'ld like to see a sample code or something which can be re-producible.

**Comment by elie222** [comment]
I don't actually know where it's coming from. I don't use the picker
package. Some other package must be using it and causing the error.

**Comment by arunoda** [comment]
Actually, it can be fast-render. If that's the case, try to isolate the publication which cause this and send me. Still, I'm not exactly sure where this is happening.

**Comment by franxois** [comment]
Hi,
I have this error with this code

```
Picker.route('/frames', function(params, req, res, next) {
    if (req.method == "POST") {
      req.on("data", function(data) {
            var data = JSON.parse(data);
                    mongo_trames.update({
                    
 }, {
                         $push: {
                             data: [trame.ts, trame.nb]
                         }
                     }, {
                         upsert: true
                     });
                }
            }
        });
    }
    res.end();
});
```
The error appears when I add the mongo.update() part
That may not be related directly to Fiber but how do we have to deal with the "req.on("data",callback)" think the meteor way ?? I try Meteor.wrapAsync without success :(

**Comment by zimt28** [comment]
What about `Meteor.bindEnvironment`?

**Comment by gustawdaniel** [comment]
I too have problem with this error when I trying to use mongo handling requests.
