### ISSUE TITLE
route specific body parsing?

### ISSUE THREAD

**Issue by dcsan** [meteorhacks/picker#36]
wondering if you support this type of api where we can just add parsing to a specific route, as per the express/bodyparser docs:

https://github.com/expressjs/body-parser#express-route-specific

```
let rawParser = bodyParser.raw();

Picker.route('/rebot/loadRive', rawParser, function(params, req, res) { ...

```

it seems to error so not sure if this is possible:

```
TypeError: Cannot read property 'transfer-encoding' of undefined
    at Function.hasbody (/Users/dc/dev/rikai/chatrobot/app/.meteor/local/isopacks/npm-container/npm/node_modules/body-parser/node_modules/type-is/index.js:93:21)
    at rawParser (/Users/dc/dev/rikai/chatrobot/app/.meteor/local/isopacks/npm-container/npm/node_modules/body-parser/lib/types/raw.js:63:17)
    at doCall (packages/meteorhacks_picker/packages/meteorhacks_picker.js:106:1)
RiveScript Interpreter v1.2.0 Initialized.  >>>> 
```

**Comment by arunoda** [comment]
Currently it's supported via creating a [group](https://github.com/meteorhacks/picker#filtering-and-sub-routes) and adding a middleware.

**Comment by dcsan** [comment]
thanks!
