### ISSUE TITLE
"Internal Server Error" only with production bundle, but works great on localhost.

### ISSUE THREAD

**Issue by trusktr** [meteorhacks/picker#51]
When I `meteor build` my app, I get an "Internal Server Error" on any picker routes. But it works fine on localhost:3000.

The error output looks like this:

```
TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1184:7)
    at server/main.js:27:47
    at doCall (packages/meteorhacks_picker.js:128:14)
```

Any idea why this happens?

**Comment by trusktr** [comment]
Reproduction: http://github.com/trusktr/trusktr.io

- At the root of the repo, run `cd src && npm install && npm run build`
- `cd ../meteor-app`
- `npm install`
- `meteor build --architecture os.linux.x86_64 ../some-place --directory --debug`
- try to run the generated bundle, you will get the error in meteorhacks/picker.

You can also run `meteor` inside the `meteor-app` folder to run the app in dev mode, and `picker` works if you run it that way.

**Comment by trusktr** [comment]
Oh, then once your run the bundle (or the app in dev mode) visit `localhost:3000/flipDiagonal` to see the error in production mode, or to see it working in dev mode.

**Comment by trusktr** [comment]
@arunoda Any ideas?

**Comment by trusktr** [comment]
I guess I'll have to give iron:router a try to hopefully get things working. I conceptually like Picker better though.

**Comment by trusktr** [comment]
Hello, anyone there?
